[project]
name = "voice-bridge-claude"
version = "1.0.0"
description = "Voice Bridge para Claude Desktop - Patología Molecular"
dependencies = [
    "azure-cognitiveservices-speech>=1.35.0",
    "pyautogui>=0.9.54",
    "pynput>=1.7.6",
    "pyyaml>=6.0.1",
    "requests>=2.31.0",
    "python-dotenv>=1.0.0",
    "tkinter-tooltip>=2.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=22.0.0",
    "flake8>=4.0.0",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
